name = "rust-worker-demo"
type = "rust"
account_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
workers_dev = true
route = "" # "*.example.com/*"
zone_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
kv-namespaces = [
    { binding = "Document", id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }
]
